dist: trusty
language: rust
services: docker
sudo: required

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-musl

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh

script:
  - bash ci/script.sh

after_script:
  - set +e

after_success: |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        # Uncomment the following line for coveralls.io
        # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

        # Uncomment the following two lines create and upload a report for codecov.io
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    fi
