sudo: required

language: rust

addons:
  apt:
    packages:
      - libssl-dev
      - musl-tools
      - gcc-multilib
      - g++-multilib

os:
- linux

rust:
- stable
- beta
- nightly

env:
- TARGET=i686-unknown-linux-musl CC=musl-gcc
- TARGET=x86_64-unknown-linux-gnu
- TARGET=x86_64-unknown-linux-musl

matrix:
  allow_failures:
    - rust: nightly

script:
- if [[ $TARGET != "x86_64-unknown-linux-gnu" ]]; then rustup target add $TARGET; fi
- cargo test --target=$TARGET

after_success: |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        # Uncomment the following line for coveralls.io
        # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

        # Uncomment the following two lines create and upload a report for codecov.io
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    fi
